
services:
  app:
    image: dev.chat-ws-server:latest
    container_name: dev.chat-ws-server

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env

    restart: unless-stopped

 